apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gvs-app-ingress
  namespace: egrand
  labels:
    app.kubernetes.io/name: gvs-app
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: egrand-real-ip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: help.egrand.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gvs-app-service
            port:
              number: 8080
