apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gvs-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Cloudflare / Reverse Proxy real IP handling
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - host: app.grandvendorservice.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gvs-app-service
            port:
              number: 8080
